version: '3.1'

services:
  db:
    container_name: postgres
    hostname: postgres
    image: postgres:latest
    volumes:
      - ./data/db:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_DB: sparkifydb
      POSTGRES_USER: student
      POSTGRES_PASSWORD: student
    ports:
      - 5432:5432